export const GET_ALL_ASSIGNMENTS_SUCCESS = "GET_ALL_ASSIGNMENTS_SUCCESS";
export const GET_ALL_ASSIGNMENTS_START = "GET_ALL_ASSIGNMENTS_START";
export const GET_ALL_ASSIGNMENTS_FAIL = "GET_ALL_ASSIGNMENTS_FAIL";

export const SET_HEADER_NAME = "SET_HEADER_NAME";


